name: album-log
version: '0.1.0.0'
category: Sound
author: ZedPea
maintainer: zp+github@zacharypalmer.co.uk
license: BSD3
dependencies:
- base >=4.9 && <4.10
- time
- parsec
- lens
- cmdargs
- directory
- transformers
- haskeline
executables:
  album-log:
    main: Main.hs
    source-dirs: src
